### ISSUE TITLE
Game is updated.

### ISSUE THREAD

**Issue by NolieRavioli** [srive/CC2WeightMod#1]
I made a python program that recreates your code. Here are the updated values for the new update (steam version (working today)):

expected_hash = "37847c780814143036c3ddea29954ebc80a8d8a4edacd3a8a5bac00035a64f2a"
weight_offset = 5008846

**Comment by srive** [comment]
I'm still seeing the game on 1.5.2 with no new updates. I did recheck the offset and it was incorrect and I've updated it accordingly. Although I'm not sure where you got yours from as that is not the updated one that I found
